table FactEncounter

	measure 'Total Encounters' = COUNTROWS(FactEncounter)
		formatString: #,0

	measure 'Avg Length of Stay' = AVERAGE(FactEncounter[LengthOfStayDays])
		formatString: #,0.0

	measure 'Readmission Rate %' = DIVIDE(CALCULATE(COUNTROWS(FactEncounter), FactEncounter[IsReadmission] = TRUE()), COUNTROWS(FactEncounter))
		formatString: 0.0%

	measure 'Total Charges' = SUM(FactEncounter[TotalCharges])
		formatString: \$#,0

	column EncounterKey
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: EncounterKey

	column DateKey
		dataType: int64
		summarizeBy: none
		sourceColumn: DateKey

	column PatientKey
		dataType: int64
		summarizeBy: none
		sourceColumn: PatientKey

	column ProviderKey
		dataType: int64
		summarizeBy: none
		sourceColumn: ProviderKey

	column DepartmentKey
		dataType: int64
		summarizeBy: none
		sourceColumn: DepartmentKey

	column DiagnosisKey
		dataType: int64
		summarizeBy: none
		sourceColumn: DiagnosisKey

	column LengthOfStayDays
		dataType: int64
		summarizeBy: sum
		sourceColumn: LengthOfStayDays

	column IsReadmission
		dataType: boolean
		summarizeBy: none
		sourceColumn: IsReadmission

	column TotalCharges
		dataType: double
		summarizeBy: sum
		sourceColumn: TotalCharges

	partition FactEncounter = m
		mode: import
		source =
				let
				    Source = Sql.Database(SqlEndpoint, SqlDatabase),
				    Data = Source{[Schema="dbo",Item="fact_encounter"]}[Data]
				in
				    Data

